version: '3'
services:

  web_back:
    build:
      context: ./Back/area
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    #environment: # Pass environment variables to the service
      #SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/AreaApi?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      #SPRING_DATASOURCE_USERNAME: areaApp
      #SPRING_DATASOURCE_PASSWORD: areaApp  
    networks: # Networks to join (Services on the same network can communicate with each other using container name)
      - spring-net #turingmysql

  mysql:
    build: ./Database_area
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Area
      MYSQL_USER: areaApp
      MYSQL_PASSWORD: areaApp
    volumes:
      - db-data:/var/lib/mysql
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - spring-net #turingmysql
    #tty: true
    #expose:
      #- 3307
    #ports:
      #- "3307:3306"
    
# Volumes



  web_front:
    build: 
      context: ./Front/Area
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  
    #command: mvn spring-boot:run

networks:
  #turingmysql:
  spring-net:
    driver: bridge

volumes:
  db-data:
