DROP SCHEMA IF EXISTS Area;

CREATE SCHEMA Area;
USE Area ;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NULL DEFAULT NULL,
  username VARCHAR(255) NULL DEFAULT NULL,
  password VARCHAR(255) NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS objects (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  person BIGINT(20),
  action VARCHAR(255) NULL DEFAULT NULL,
  reaction TEXT NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);