jenkins:
  systemMessage: "Welcome to the Whanos Jenkins Instance."
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: ${JENKINS_USER_ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

jobs:
  - file: /var/lib/jenkins/job_dsl.groovy