FROM maven:3.9.0-eclipse-temurin-17-alpine

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]

ONBUILD COPY . /app

ONBUILD WORKDIR /app

ONBUILD RUN mvn package -f app/pom.xml

ONBUILD RUN mv app/target/app.jar ./app.jar

ONBUILD RUN find . -not -name app.jar -delete

ONBUILD CMD ["java", "-jar", "app.jar"]
